# Site settings

title: Capital Place # Title
email: fuzzy.hedge@gmail.com # Email

description: > # Ignore newlines until "baseurl:"
    The ratio of two standard normal distributions is a fat-tailed distribution.
baseurl: "" # Subpath
url: "http://capital.place" # Hostname w protocol

# Build settings
markdown: kramdown
highlighter: rouge

exclude: ['_sass', 'README.markdown', 'Rakefile', 'Gemfile']

gems:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: atom.xml

sass:
    sass_dir: _sass
    style: compressed

# Social links.
twitter_username:     # Replace
github_username:      # Replace
linkedin_username:    # Replace
google_plus_username: # Replace
facebook_username:    # Replace
dribbble_username:    # Replace

# Blog Configuration
frontpage_posts: 0
excerpt_posts: 0

twitter:
  username: 